/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculador.h"

float *
sum_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;


	result = argp->num1 + argp->num2;


	return &result;
}

float *
res_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->num1 - argp->num2;

	 

	return &result;
}

float *
mul_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;
	result = argp->num1 * argp->num2;


	return &result;
}

float *
div_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->num1 / argp->num2;


	return &result;
}
